const STORAGE_KEY = "jr_saas_questions_v1";
const ATTEMPTS_KEY = "jr_saas_attempts_v1";
const defaultQuestions = [
  {id: crypto.randomUUID(), statement: "O princípio da eficiência busca o melhor resultado com o uso racional dos recursos públicos.", explanation: "Linguagem equilibrada e alinhada ao texto administrativo. A técnica favorece CERTO.", bank: "CESPE", type: "certo_errado", answer: true, difficulty: "fácil"},
  {id: crypto.randomUUID(), statement: "Os direitos fundamentais são sempre absolutos e não admitem qualquer tipo de limitação.", explanation: "A palavra 'sempre' acende alerta. Em regra, absolutos costumam indicar erro.", bank: "CESPE", type: "certo_errado", answer: false, difficulty: "fácil"},
  {id: crypto.randomUUID(), statement: "A Administração Pública pode anular seus próprios atos quando eivados de ilegalidade.", explanation: "A afirmativa acompanha o entendimento clássico da autotutela administrativa.", bank: "FCC", type: "certo_errado", answer: true, difficulty: "médio"},
  {id: crypto.randomUUID(), statement: "A publicidade administrativa é obrigatória em todos os casos, sem exceções legais.", explanation: "O termo 'todos' torna a frase suspeita. Existem hipóteses legais de sigilo e restrição.", bank: "FGV", type: "certo_errado", answer: false, difficulty: "médio"},
  {id: crypto.randomUUID(), statement: "O poder de polícia permite restringir direitos individuais em favor do interesse coletivo.", explanation: "A frase está juridicamente adequada e usa linguagem equilibrada.", bank: "VUNESP", type: "certo_errado", answer: true, difficulty: "fácil"},
  {id: crypto.randomUUID(), statement: "A moralidade administrativa integra expressamente os princípios constitucionais da administração pública.", explanation: "A moralidade está no caput do art. 37 da Constituição. Aqui, a técnica confirma CERTO.", bank: "FCC", type: "certo_errado", answer: true, difficulty: "fácil"},
  {id: crypto.randomUUID(), statement: "O concurso público pode ser dispensado para qualquer cargo efetivo, conforme conveniência da administração.", explanation: "Afirmativa ampla demais. 'Qualquer cargo efetivo' desmonta a frase.", bank: "FGV", type: "certo_errado", answer: false, difficulty: "difícil"}
];
const state = {questions: loadQuestions(), attempts: loadAttempts(), editingId: null, quiz: {step: "intro", filters: {bank: "CESPE", type: "certo_errado"}, questions: [], index: 0, score: 0, answers: []}};
function loadQuestions(){const raw=localStorage.getItem(STORAGE_KEY); if(!raw){localStorage.setItem(STORAGE_KEY, JSON.stringify(defaultQuestions)); return [...defaultQuestions];} try{return JSON.parse(raw);}catch{return [...defaultQuestions];}}
function saveQuestions(){localStorage.setItem(STORAGE_KEY, JSON.stringify(state.questions));}
function loadAttempts(){const raw=localStorage.getItem(ATTEMPTS_KEY); if(!raw) return []; try{return JSON.parse(raw);}catch{return [];}}
function saveAttempts(){localStorage.setItem(ATTEMPTS_KEY, JSON.stringify(state.attempts));}
const qs=s=>document.querySelector(s); const qsa=s=>[...document.querySelectorAll(s)];
function switchView(view){qsa('.view').forEach(v=>v.classList.remove('active')); qs('#view-'+view).classList.add('active'); qsa('.nav-btn').forEach(b=>b.classList.toggle('active', b.dataset.view===view)); if(view==='dashboard') renderDashboard(); if(view==='admin') renderQuestionsTable(); if(view==='quiz') renderQuiz();}
function renderDashboard(){qs('#statQuestions').textContent=state.questions.length; qs('#statAttempts').textContent=state.attempts.length; const avg=state.attempts.length?Math.round(state.attempts.reduce((a,b)=>a+b.percent,0)/state.attempts.length):0; qs('#statAverage').textContent=avg+'%'; const last=state.attempts[0]; qs('#statLast').textContent=last?`${last.score}/${last.total}`:'-'; qs('#attemptsList').innerHTML=state.attempts.length?state.attempts.map(a=>`<div class="list-item"><strong>${a.score}/${a.total} acertos</strong><div class="muted">${a.percent}% · ${a.bank} · ${new Date(a.createdAt).toLocaleString('pt-BR')}</div></div>`).join(''):`<div class="list-item muted">Nenhum simulado realizado ainda.</div>`; const grouped={}; state.questions.forEach(q=>grouped[q.bank]=(grouped[q.bank]||0)+1); qs('#bankBreakdown').innerHTML=Object.keys(grouped).length?Object.entries(grouped).map(([bank,count])=>`<div class="list-item"><strong>${bank}</strong><div class="muted">${count} questão(ões)</div></div>`).join(''):`<div class="list-item muted">Sem dados.</div>`;}
function renderQuestionsTable(){const search=qs('#searchInput').value.toLowerCase().trim(); const bank=qs('#filterBank').value; const type=qs('#filterType').value; const filtered=state.questions.filter(q=>{const okSearch=!search||q.statement.toLowerCase().includes(search); const okBank=!bank||q.bank===bank; const okType=!type||q.type===type; return okSearch&&okBank&&okType;}); qs('#questionsTable').innerHTML=filtered.length?filtered.map(q=>`<tr><td>${escapeHtml(q.statement)}</td><td>${q.bank}</td><td>${q.type==='certo_errado'?'Certo/Errado':'Múltipla'}</td><td>${q.answer?'Certo':'Errado'}</td><td><div class="action-row"><button class="ghost mini" onclick="openModal('${q.id}')">Editar</button><button class="ghost mini" onclick="duplicateQuestion('${q.id}')">Duplicar</button><button class="ghost mini" onclick="deleteQuestion('${q.id}')">Excluir</button></div></td></tr>`).join(''):`<tr><td colspan="5" class="muted">Nenhuma questão encontrada.</td></tr>`;}
function openModal(id=null){state.editingId=id; const current=state.questions.find(q=>q.id===id); qs('#modalTitle').textContent=current?'Editar questão':'Nova questão'; qs('#formStatement').value=current?.statement||''; qs('#formExplanation').value=current?.explanation||''; qs('#formBank').value=current?.bank||'CESPE'; qs('#formType').value=current?.type||'certo_errado'; qs('#formAnswer').value=String(current?.answer??true); qs('#formDifficulty').value=current?.difficulty||'fácil'; qs('#btnDeleteQuestion').classList.toggle('hidden', !current); qs('#questionModal').classList.remove('hidden');}
function closeModal(){qs('#questionModal').classList.add('hidden');}
function saveQuestionFromForm(){const payload={statement:qs('#formStatement').value.trim(), explanation:qs('#formExplanation').value.trim(), bank:qs('#formBank').value, type:qs('#formType').value, answer:qs('#formAnswer').value==='true', difficulty:qs('#formDifficulty').value}; if(!payload.statement||!payload.explanation){alert('Preencha enunciado e explicação.'); return;} if(state.editingId){state.questions=state.questions.map(q=>q.id===state.editingId?{...q,...payload}:q);}else{state.questions.unshift({id:crypto.randomUUID(),...payload});} saveQuestions(); closeModal(); renderQuestionsTable(); renderDashboard();}
function duplicateQuestion(id){const current=state.questions.find(q=>q.id===id); if(!current) return; state.questions.unshift({...current,id:crypto.randomUUID(),statement:current.statement+' (cópia)'}); saveQuestions(); renderQuestionsTable(); renderDashboard();}
function deleteQuestion(id){if(!confirm('Excluir esta questão?')) return; state.questions=state.questions.filter(q=>q.id!==id); saveQuestions(); renderQuestionsTable(); renderDashboard(); if(state.editingId===id) closeModal();}
function exportJSON(){const blob=new Blob([JSON.stringify(state.questions,null,2)],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='jr-gabaritando-questoes.json'; a.click(); URL.revokeObjectURL(url);}
function importJSON(file){const reader=new FileReader(); reader.onload=e=>{try{const parsed=JSON.parse(e.target.result); if(!Array.isArray(parsed)) throw new Error(); state.questions=parsed.map(item=>({id:item.id||crypto.randomUUID(),statement:item.statement||'',explanation:item.explanation||'',bank:item.bank||'Outra',type:item.type||'certo_errado',answer:Boolean(item.answer),difficulty:item.difficulty||'médio'})); saveQuestions(); renderQuestionsTable(); renderDashboard(); alert('Questões importadas com sucesso.');}catch{alert('JSON inválido.');}}; reader.readAsText(file);}
function resetDemo(){if(!confirm('Restaurar a base demo e apagar histórico local?')) return; state.questions=[...defaultQuestions]; state.attempts=[]; saveQuestions(); saveAttempts(); renderDashboard(); renderQuestionsTable(); renderQuiz();}
function buildQuizPool(){const pool=state.questions.filter(q=>(!state.quiz.filters.bank||q.bank===state.quiz.filters.bank)&&q.type===state.quiz.filters.type); return shuffle([...pool]).slice(0,5);}
function startQuizJourney(){state.quiz.step='warmup'; state.quiz.index=0; state.quiz.score=0; state.quiz.answers=[]; switchView('quiz'); renderQuiz();}
function renderQuiz(){const stage=qs('#quizStage'); const step=state.quiz.step; if(step==='intro'){stage.innerHTML=`<div class="quiz-wrap"><div class="quiz-card"><span class="pill">Onboarding</span><h2 class="quiz-title">Antes de começar, me conta uma coisa.</h2><p class="muted">Vou personalizar a sua experiência com base no perfil do seu treino.</p><div class="option-grid">${['CESPE','FCC','FGV','VUNESP','Outra'].map(bank=>`<button class="option-btn ${state.quiz.filters.bank===bank?'selected':''}" onclick="setQuizBank('${bank}')">${bank}</button>`).join('')}</div><div class="option-grid"><button class="option-btn ${state.quiz.filters.type==='certo_errado'?'selected':''}" onclick="setQuizType('certo_errado')">Certo ou Errado</button><button class="option-btn ${state.quiz.filters.type==='multipla'?'selected':''}" onclick="setQuizType('multipla')">Múltipla escolha</button></div><div class="cta-row"><button class="gold big" onclick="startQuizJourney()">Ver o hack</button></div></div></div>`; return;}
if(step==='warmup'){stage.innerHTML=`<div class="quiz-wrap"><div class="quiz-card"><span class="pill">Aquecimento</span><h2 class="quiz-title">Questão rápida</h2><p>“Os direitos fundamentais são sempre absolutos.”</p><div class="answer-actions"><button class="answer-btn true" onclick="resolveWarmup(true)">CERTO</button><button class="answer-btn false" onclick="resolveWarmup(false)">ERRADO</button></div><div id="warmupFeedback"></div></div></div>`; return;}
if(step==='hack'){stage.innerHTML=`<div class="quiz-wrap"><div class="quiz-card"><span class="pill">Hack aplicado</span><h2 class="quiz-title">Entenda a técnica antes do simulado</h2><div class="hero-grid"><div class="premium-card"><h3>Segredo 1</h3><p>Palavras absolutas como “sempre”, “nunca” e “todos” geralmente indicam erro.</p></div><div class="premium-card"><h3>Segredo 2</h3><p>Frases moderadas, compatíveis com a lei e sem exageros, tendem a estar corretas.</p></div><div class="premium-card"><h3>Segredo 3</h3><p>Use a técnica como filtro, não como chute cego. A banca e o tema importam.</p></div></div><div class="cta-row"><button class="gold big" onclick="beginQuestionLoop()">Iniciar simulado</button></div></div></div>`; return;}
if(step==='running'){const current=state.quiz.questions[state.quiz.index]; if(!current){finalizeQuiz(); return;} stage.innerHTML=`<div class="quiz-wrap"><div class="quiz-card"><div class="progress-top"><strong>Questão ${state.quiz.index+1} de ${state.quiz.questions.length}</strong><div class="progress-dots">${state.quiz.questions.map((_,idx)=>`<span class="dot ${idx<state.quiz.index?'done':idx===state.quiz.index?'current':''}"></span>`).join('')}</div></div><span class="pill">${current.bank} · ${current.difficulty}</span><h2 class="quiz-title">${escapeHtml(current.statement)}</h2><div class="answer-actions"><button class="answer-btn true" onclick="submitAnswer(true)">CERTO</button><button class="answer-btn false" onclick="submitAnswer(false)">ERRADO</button></div></div></div>`; return;}
if(step==='feedback'){const answer=state.quiz.answers[state.quiz.answers.length-1]; stage.innerHTML=`<div class="quiz-wrap"><div class="quiz-card"><span class="pill">Hack aplicado</span><div class="feedback-box ${answer.correct?'correct':'wrong'}"><h2>${answer.correct?'Você acertou.':'Você errou.'}</h2><p><strong>Resposta correta:</strong> ${answer.correctAnswer?'CERTO':'ERRADO'}</p><p>${escapeHtml(answer.explanation)}</p></div><div class="cta-row"><button class="gold big" onclick="advanceQuiz()">Continuar</button></div></div></div>`; return;}
if(step==='result'){const total=state.quiz.questions.length; const percent=Math.round((state.quiz.score/total)*100); const message=percent>=80?'Excelente leitura de padrão. Você está dominando bem a técnica.':percent>=60?'Bom desempenho. Ajuste os detalhes e continue praticando.':'Você entendeu a proposta. Agora precisa repetir o treino até ganhar velocidade.'; stage.innerHTML=`<div class="result-card"><span class="pill">Resultado final</span><h2 class="quiz-title">Seu desempenho</h2><div class="result-big">${state.quiz.score}/${total}</div><p class="muted">${message}</p><div class="result-grid"><div class="result-chip"><strong>${percent}%</strong><div class="muted">Aproveitamento</div></div><div class="result-chip"><strong>${state.quiz.filters.bank}</strong><div class="muted">Banca selecionada</div></div><div class="result-chip"><strong>${state.quiz.filters.type==='certo_errado'?'Certo/Errado':'Múltipla'}</strong><div class="muted">Formato</div></div></div><div class="cta-row"><button class="gold big" onclick="restartQuiz()">Fazer novamente</button><button class="ghost big" onclick="switchView('dashboard')">Ir para dashboard</button></div></div>`; return;}}
function setQuizBank(bank){state.quiz.filters.bank=bank; renderQuiz();}
function setQuizType(type){state.quiz.filters.type=type; renderQuiz();}
function resolveWarmup(choice){const box=qs('#warmupFeedback'); const correct=choice===false; box.innerHTML=`<div class="feedback-box ${correct?'correct':'wrong'}"><h3>${correct?'Acertou.':'Errou.'}</h3><p>A palavra <strong>sempre</strong> é um gatilho clássico de atenção. Absolutos exigem cuidado.</p><div class="cta-row"><button class="gold" onclick="goToHack()">Continuar</button></div></div>`;}
function goToHack(){state.quiz.step='hack'; renderQuiz();}
function beginQuestionLoop(){const pool=buildQuizPool(); if(pool.length<3){alert('Você precisa ter pelo menos 3 questões do filtro escolhido. Cadastre mais no admin.'); switchView('admin'); return;} state.quiz.questions=pool; state.quiz.index=0; state.quiz.score=0; state.quiz.answers=[]; state.quiz.step='running'; renderQuiz();}
function submitAnswer(choice){const current=state.quiz.questions[state.quiz.index]; const correct=choice===current.answer; if(correct) state.quiz.score++; state.quiz.answers.push({questionId:current.id, choice, correct, correctAnswer:current.answer, explanation:current.explanation}); state.quiz.step='feedback'; renderQuiz();}
function advanceQuiz(){state.quiz.index++; if(state.quiz.index>=state.quiz.questions.length){finalizeQuiz();} else {state.quiz.step='running'; renderQuiz();}}
function finalizeQuiz(){const total=state.quiz.questions.length; const percent=Math.round((state.quiz.score/total)*100); state.attempts.unshift({score:state.quiz.score,total,percent,bank:state.quiz.filters.bank,createdAt:new Date().toISOString()}); state.attempts=state.attempts.slice(0,15); saveAttempts(); state.quiz.step='result'; renderQuiz(); renderDashboard();}
function restartQuiz(){state.quiz.step='intro'; state.quiz.questions=[]; state.quiz.index=0; state.quiz.score=0; state.quiz.answers=[]; renderQuiz();}
function escapeHtml(str){return String(str).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
function shuffle(arr){for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1)); [arr[i],arr[j]]=[arr[j],arr[i]];} return arr;}
qsa('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>switchView(btn.dataset.view))); qs('#btnGoDashboard').addEventListener('click',()=>switchView('dashboard')); qs('#btnGoAdmin').addEventListener('click',()=>switchView('admin')); qs('#btnStartJourney').addEventListener('click',()=>switchView('quiz')); qs('#btnOpenAdmin').addEventListener('click',()=>switchView('admin')); qs('#btnNewQuestion').addEventListener('click',()=>openModal()); qs('#btnCloseModal').addEventListener('click',closeModal); qs('#btnSaveQuestion').addEventListener('click',saveQuestionFromForm); qs('#btnDeleteQuestion').addEventListener('click',()=>{if(state.editingId) deleteQuestion(state.editingId);}); qs('#btnExport').addEventListener('click',exportJSON); qs('#fileImport').addEventListener('change',e=>{if(e.target.files[0]) importJSON(e.target.files[0]); e.target.value='';}); qs('#btnResetDemo').addEventListener('click',resetDemo); qs('#searchInput').addEventListener('input',renderQuestionsTable); qs('#filterBank').addEventListener('change',renderQuestionsTable); qs('#filterType').addEventListener('change',renderQuestionsTable); state.quiz.step='intro'; renderDashboard(); renderQuestionsTable(); renderQuiz(); window.openModal=openModal; window.deleteQuestion=deleteQuestion; window.duplicateQuestion=duplicateQuestion; window.setQuizBank=setQuizBank; window.setQuizType=setQuizType; window.startQuizJourney=startQuizJourney; window.resolveWarmup=resolveWarmup; window.goToHack=goToHack; window.beginQuestionLoop=beginQuestionLoop; window.submitAnswer=submitAnswer; window.advanceQuiz=advanceQuiz; window.restartQuiz=restartQuiz; window.switchView=switchView;
